allowBuilds:
  dtrace-provider: true
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: true
  unrs-resolver: true
patchedDependencies:
  onnxruntime-react-native@1.24.3: patches/onnxruntime-react-native@1.24.3.patch
